### ISSUE TITLE
ios跑不通

### ISSUE THREAD

**Issue by william-xue** [fmtjava/ReactNative_Eyepetizer#1]
error: /Downloads/ReactNative_Eyepetizer-main/ios/Pods/Target Support Files/Pods-reactnative_eyepetizer/Pods-reactnative_eyepetizer.debug.xcconfig: unable to open file (in target "reactnative_eyepetizer" in project "reactnative_eyepetizer") (in target 'reactnative_eyepetizer' from project 'reactnative_eyepetizer')
warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the reactnative_eyepetizer editor. (in target 'reactnative_eyepetizer' from project 'reactnative_eyepetizer')

**Comment by fmtjava** [comment]
试一下:
cd ios
pod install
yarn ios

**Comment by william-xue** [comment]
> error: /Downloads/ReactNative_Eyepetizer-main/ios/Pods/Target Support Files/Pods-reactnative_eyepetizer/Pods-reactnative_eyepetizer.debug.xcconfig: unable to open file (in target "reactnative_eyepetizer" in project "reactnative_eyepetizer") (in target 'reactnative_eyepetizer' from project 'reactnative_eyepetizer')
> warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the reactnative_eyepetizer editor. (in target 'reactnative_eyepetizer' from project 'reactnative_eyepetizer')
经过不懈的努力 现在OK了

**Comment by william-xue** [comment]
export function createHotTabModel(namespace: string) {
  if (!cached.get(namespace)) {
    const model = modelExtend(hotTab, {namespace});
    app.model(model);
    cached.set(model.namespace, true);
  }
}  
动态加载model在什么场景上需要 业务层面

**Comment by fmtjava** [comment]
多个Tab页面需要要到，比如热门模块，周排行/月排行/总排行都需要一个独立的model
